"""init migration

Revision ID: 027a79ca5e8c
Revises: 25c007f9fa47
Create Date: 2025-12-15 20:06:07.479724

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "027a79ca5e8c"
down_revision: Union[str, Sequence[str], None] = "25c007f9fa47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_members",
        "role",
        existing_type=postgresql.ENUM("OWNER", "MANAGER", "MEMBER", name="projectrole"),
        type_=sa.Enum("OWNER", "MANAGER", "MEMBER", name="projectrole", native_enum=False),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_project_members_project_id"),
        "project_members",
        type_="unique",
    )
    op.create_unique_constraint(
        "idx_unique_project_user", "project_members", ["project_id", "user_id"]
    )
    op.alter_column(
        "tasks",
        "priority",
        existing_type=postgresql.ENUM("LOW", "MEDIUM", "HIGH", "CRITICAL", name="taskpriority"),
        type_=sa.Enum(
            "LOW",
            "MEDIUM",
            "HIGH",
            "CRITICAL",
            name="taskpriority",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "priority",
        existing_type=sa.Enum(
            "LOW",
            "MEDIUM",
            "HIGH",
            "CRITICAL",
            name="taskpriority",
            native_enum=False,
        ),
        type_=postgresql.ENUM("LOW", "MEDIUM", "HIGH", "CRITICAL", name="taskpriority"),
        existing_nullable=False,
    )
    op.drop_constraint("idx_unique_project_user", "project_members", type_="unique")
    op.create_unique_constraint(
        op.f("uq_project_members_project_id"),
        "project_members",
        ["project_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "project_members",
        "role",
        existing_type=sa.Enum("OWNER", "MANAGER", "MEMBER", name="projectrole", native_enum=False),
        type_=postgresql.ENUM("OWNER", "MANAGER", "MEMBER", name="projectrole"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
