"""update invite model migration

Revision ID: 40efe5e0c1b7
Revises: 2041e17e1d0d
Create Date: 2025-12-16 04:41:21.960370

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40efe5e0c1b7"
down_revision: Union[str, Sequence[str], None] = "2041e17e1d0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_invitations",
        sa.Column("max_uses", sa.Integer(), nullable=True),
    )
    op.add_column(
        "project_invitations",
        sa.Column("used_count", sa.Integer(), nullable=False),
    )
    op.drop_column("project_invitations", "is_used")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_invitations",
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("project_invitations", "used_count")
    op.drop_column("project_invitations", "max_uses")
    # ### end Alembic commands ###
