"""add tasks_limit to columns

Revision ID: e385a69fcf23
Revises: 40efe5e0c1b7
Create Date: 2025-12-16 05:08:03.924545

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e385a69fcf23"
down_revision: Union[str, Sequence[str], None] = "40efe5e0c1b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("board_columns", sa.Column("tasks_limit", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("board_columns", "tasks_limit")
    # ### end Alembic commands ###
