"""add color to projects and tags

Revision ID: 4b1f02efc194
Revises: e385a69fcf23
Create Date: 2025-12-22 00:40:00.772884

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b1f02efc194"
down_revision: Union[str, Sequence[str], None] = "e385a69fcf23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_project_members_user",
        "project_members",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "projects",
        sa.Column(
            "color",
            sa.String(length=9),
            server_default="#3B82F6",
            nullable=False,
        ),
    )
    op.alter_column(
        "tags",
        "color",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=9),
        existing_nullable=False,
    )
    op.create_index("idx_tasks_assignee", "tasks", ["assignee_id"], unique=False)
    op.create_index(
        "idx_tasks_column_position",
        "tasks",
        ["column_id", "position"],
        unique=False,
    )
    op.create_index("idx_tasks_project", "tasks", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_project", table_name="tasks")
    op.drop_index("idx_tasks_column_position", table_name="tasks")
    op.drop_index("idx_tasks_assignee", table_name="tasks")
    op.alter_column(
        "tags",
        "color",
        existing_type=sa.String(length=9),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("projects", "color")
    op.drop_index("idx_project_members_user", table_name="project_members")
    # ### end Alembic commands ###
