"""add task deadline

Revision ID: 029370bc7f4a
Revises: 821ce0f817ff
Create Date: 2026-05-04 00:47:19.538197

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "029370bc7f4a"
down_revision: Union[str, Sequence[str], None] = "821ce0f817ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "deadline_at")
    # ### end Alembic commands ###
