"""make task priority optional

Revision ID: bcea414f0c52
Revises: 029370bc7f4a
Create Date: 2026-05-04 00:53:37.915269

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcea414f0c52"
down_revision: Union[str, Sequence[str], None] = "029370bc7f4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "priority", existing_type=sa.VARCHAR(length=8), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE tasks SET priority = 'MEDIUM' WHERE priority IS NULL")
    op.alter_column("tasks", "priority", existing_type=sa.VARCHAR(length=8), nullable=False)
    # ### end Alembic commands ###
