"""add yandex auth fields

Revision ID: 821ce0f817ff
Revises: 0c8ec9b25887
Create Date: 2026-05-03 23:29:18.772741

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "821ce0f817ff"
down_revision: Union[str, Sequence[str], None] = "0c8ec9b25887"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("yandex_id", sa.String(length=64), nullable=True))
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.create_index(op.f("ix_users_yandex_id"), "users", ["yandex_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_yandex_id"), table_name="users")
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("users", "yandex_id")
    # ### end Alembic commands ###
