"""add new indexes

Revision ID: 0c8ec9b25887
Revises: 4b1f02efc194
Create Date: 2026-03-08 02:16:48.517299

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c8ec9b25887"
down_revision: Union[str, Sequence[str], None] = "4b1f02efc194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_columns_project_pos",
        "board_columns",
        ["project_id", "position"],
        unique=False,
    )
    op.create_index(
        "idx_project_invitations_project_created",
        "project_invitations",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_project_members_project_joined",
        "project_members",
        ["project_id", "joined_at"],
        unique=False,
    )
    op.create_index(
        "idx_task_tags_tag_task",
        "task_tags",
        ["tag_id", "task_id"],
        unique=False,
    )
    op.create_index(
        "idx_tasks_project_updated",
        "tasks",
        ["project_id", "updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_project_updated", table_name="tasks")
    op.drop_index("idx_task_tags_tag_task", table_name="task_tags")
    op.drop_index("idx_project_members_project_joined", table_name="project_members")
    op.drop_index(
        "idx_project_invitations_project_created",
        table_name="project_invitations",
    )
    op.drop_index("idx_columns_project_pos", table_name="board_columns")
    # ### end Alembic commands ###
