[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioboto3>=15.5.0",
    "alembic>=1.17.0",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.118.0",
    "filetype>=1.2.0",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "orjson>=3.11.4",
    "pip>=25.3",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.11.10",
    "pyjwt[crypto]>=2.10.1",
    "redis>=6.4.0",
    "sqlalchemy[asyncio]>=2.0.44",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.20",
    "schemathesis>=4.7.5",
]


[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["E", "F",  "I"]
ignore = ["E501"]
